### ISSUE TITLE
Issues from the Breaking Crystal Async

### ISSUE THREAD

**Issue by palex00** [AliceMousie/crystal-ap-tracker#5]
I am only listing Tracker bugs that haven't been fixed in Main yet as of now (as far as I can tell)
- Cianwood Gym has Strength Requirement for all Trainers, instead of just Chuck and the last Gym Trainer
- PokéGear is not being auto-tracked when Vanilla

**Comment by AliceMousie** [comment]
Fixed in 0.1.0
